### ISSUE TITLE
DAQ sometimes crashes without obvious reason

### ISSUE THREAD

**Issue by JanGieseler** [LISE-B26/b26_toolkit#5]
issue from PyLabControl

**Comment by JanGieseler** [comment]
error message stack trace obtained from NI trace (error at 1955):

1948.  DAQmxCfgSampClkTiming (0x000000000AC33320, "/Dev1/PFI13", 5000, DAQmx_Val_Rising, DAQmx_Val_FiniteSamps, 276)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:28.809       Call Duration 00:00:01.365
Status: 0 (0x0)

1949.  DAQmxStartTask (0x000000000AC33320)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:30.217       Call Duration 00:00:00.082
Status: 0 (0x0)

1950.  DAQmxCreateTask ("", 0x0AC334B0)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:30.405       Call Duration 00:00:00.000
Status: 0 (0x0)

1951.  DAQmxCreateAOVoltageChan (0x000000000AC334B0, "Dev1/ao0,Dev1/ao3", "", -10, 10, DAQmx_Val_Volts, NULL)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:30.470       Call Duration 00:00:00.291
Status: 0 (0x0)

1952.  DAQmxCfgSampClkTiming (0x000000000AC334B0, "", 5000, DAQmx_Val_Rising, DAQmx_Val_FiniteSamps, 2)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:31.012       Call Duration 00:00:00.417
Status: 0 (0x0)

1953.  DAQmxWriteAnalogF64 (0x000000000AC334B0, 2, False, -1, "DAQmx_Val_GroupByChannel", {-0.381659,-0.381659}, NULL, NULL)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:31.471       Call Duration 00:00:00.004
Status: 0 (0x0)

1954.  DAQmxStartTask (0x000000000AC334B0)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:31.579       Call Duration 00:00:00.064
Status: 0 (0x0)

> **1955**.  DAQmxWaitUntilTaskDone (0x000000000AC334B0, 0.0016)
> Process ID: 0x00003EF8         Thread ID: 0x00000C8C
> Start Time: 11:51:31.689       Call Duration 00:00:00.033
> Status: -200560 (0xFFFCF090)

1956.  DAQmxGetErrorString (-200560, "Wait Until Done......Increase the", 100)
Process ID: 0x00003EF8         Thread ID: 0x00000C8C
Start Time: 11:51:31.883       Call Duration 00:00:00.174
Status: 200026 (0x30D5A)

**Comment by akabcenell** [comment]
Bug in timeout calculation caused function to occasionally take too long for short scans. Fixed in a previous push.
